/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aed_assignment1;
import DAO.PersonDetails;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Vaishali Tripathi
 */
public class ReportView1 extends javax.swing.JFrame {
    private PersonDetails personDetail;
    /**
     * Creates new form ReportView1
     */
    public ReportView1() {
        initComponents();
    }
    public ReportView1(PersonDetails personData) {
        initComponents();
        this.personDetail = personData;
        SetAllLabels();
    }
    
    private void SetAllLabels(){
        
        //Demographic Information
        FnameShowsHere.setText(personDetail.getFname());
        LnameShowsHere.setText(personDetail.getLname());
  
        //Date dobdateshow = new Date();
        dobdateshow.setText(personDetail.getDate1Str());
  
        SSNShowsHere.setText(personDetail.getSSN());
        WeightShowsHere.setText(personDetail.getWeight());
        HeightShowsHere.setText(personDetail.getHeight());
        
        //float height = Float.parseFloat(heightTxt.getText());
         //float weight = Float.parseFloat(weightTxt.getText());
         ContactShowsHere.setText(personDetail.getContact());
         
         //Address Information
         StrtAddShowsHere.setText(personDetail.getStreetAdd());
         StateShowsHere.setText(personDetail.getState());
         CityShowsHere.setText(personDetail.getCity());
         PostalCodeShowsHere.setText(personDetail.getZipCode());
         
         //Saving Account Information
         SavingAcctBalShowsHere.setText(personDetail.getSavingBankBalance());
         SavingBnkAcctNumShowsHere.setText(personDetail.getSavingBankAccNum());
         SavingBnkNameShowsHere.setText(personDetail.getSavingBankName());
         SavingBnkRoutingShowsHere.setText(personDetail.getSavingBankRouting());
         
         //Checking Account Details
         ChkAcctBalShowsHere.setText(personDetail.getCheckingBankBalance());
         ChkBnkNameShowsHere.setText(personDetail.getCheckingBankName());
         ChkBnkAcctNumShowsHere.setText(personDetail.getCheckingBankAccNum());
         ChkBnkRoutingShowsHere.setText(personDetail.getCheckingBankRouting());
         
         //License Details
         LicenseNumShowsHere.setText(personDetail.getLicenseNum());
         IssueDateShowsHere.setText(personDetail.getIssueDateStr());
         ExpiryDateShowsHere.setText(personDetail.getExpiryDateStr());
         BloodTypeShowsHere.setText(personDetail.getBloodType());
        //imagedispLbl.setIcon(personDetail.getImageURL());
        
        ImageIcon image= new ImageIcon(personDetail.getImageURL());
        
        Image xyz = image.getImage();
        Image scaledimg = xyz.getScaledInstance(180,190,java.awt.Image.SCALE_SMOOTH);
        image = new ImageIcon(scaledimg);
        imagedispLbl.setIcon(image);
        
         
         //Medical Details
         MedicalRecordNumShowsHere.setText(personDetail.getMedicalRecordNum());
         Alergy1ShowsHere.setText(personDetail.getAlergy1());
         Alergy2ShowsHere.setText(personDetail.getAlergy2());
         Alergy3ShowsHere.setText(personDetail.getAlergy3());
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        demographicPanel = new javax.swing.JPanel();
        demoInfoLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        FnameShowsHere = new javax.swing.JLabel();
        dobdateshow = new javax.swing.JLabel();
        SSNShowsHere = new javax.swing.JLabel();
        LnameShowsHere = new javax.swing.JLabel();
        AgeShowsHere = new javax.swing.JLabel();
        ContactShowsHere = new javax.swing.JLabel();
        HeightShowsHere = new javax.swing.JLabel();
        WeightShowsHere = new javax.swing.JLabel();
        addressGetPanel = new javax.swing.JPanel();
        addressInfoLabel = new javax.swing.JLabel();
        streetAddLabel = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        StrtAddShowsHere = new javax.swing.JLabel();
        CityShowsHere = new javax.swing.JLabel();
        StateShowsHere = new javax.swing.JLabel();
        PostalCodeShowsHere = new javax.swing.JLabel();
        accountDetailsPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SavingBnkNameShowsHere = new javax.swing.JLabel();
        SavingBnkRoutingShowsHere = new javax.swing.JLabel();
        SavingBnkAcctNumShowsHere = new javax.swing.JLabel();
        SavingAcctBalShowsHere = new javax.swing.JLabel();
        ChkBnkNameShowsHere = new javax.swing.JLabel();
        ChkBnkRoutingShowsHere = new javax.swing.JLabel();
        ChkBnkAcctNumShowsHere = new javax.swing.JLabel();
        ChkAcctBalShowsHere = new javax.swing.JLabel();
        driverLicPanel = new javax.swing.JPanel();
        driverLicDetPanel = new javax.swing.JLabel();
        licNumLbl = new javax.swing.JLabel();
        issueDateLbl = new javax.swing.JLabel();
        expiryDateLbl = new javax.swing.JLabel();
        bloodTypeLbl = new javax.swing.JLabel();
        LicenseNumShowsHere = new javax.swing.JLabel();
        IssueDateShowsHere = new javax.swing.JLabel();
        ExpiryDateShowsHere = new javax.swing.JLabel();
        BloodTypeShowsHere = new javax.swing.JLabel();
        imagedispLbl = new javax.swing.JLabel();
        medicalPanel = new javax.swing.JPanel();
        medicalPanelLbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MedicalRecordNumShowsHere = new javax.swing.JLabel();
        Alergy1ShowsHere = new javax.swing.JLabel();
        Alergy2ShowsHere = new javax.swing.JLabel();
        Alergy3ShowsHere = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        demographicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        demoInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        demoInfoLabel.setText("Demographic Information");

        fnameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fnameLabel.setText("First Name:");

        dobLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dobLabel.setText("Date of Birth:");

        ssnLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ssnLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ssnLabel.setText("Social Security Number:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("kgs");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("cms");

        heightLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        heightLabel.setText("Height:");

        weightLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        weightLabel.setText("Weight:");

        contactLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        contactLabel.setText("Contact Number:");

        ageLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ageLabel.setText("Age:");
        ageLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lnameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnameLabel.setText("Last Name:");

        FnameShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        FnameShowsHere.setText("FnameShowsHere");

        dobdateshow.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dobdateshow.setText("DOBShowsHere");

        SSNShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SSNShowsHere.setText("SSNShowsHere");

        LnameShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LnameShowsHere.setText("LnameShowsHere");

        AgeShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AgeShowsHere.setText("AgeShowsHere");

        ContactShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ContactShowsHere.setText("ContactShowsHere");

        HeightShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        HeightShowsHere.setText("HeightShowsHere");

        WeightShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        WeightShowsHere.setText("WeightShowsHere");

        javax.swing.GroupLayout demographicPanelLayout = new javax.swing.GroupLayout(demographicPanel);
        demographicPanel.setLayout(demographicPanelLayout);
        demographicPanelLayout.setHorizontalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ssnLabel)
                            .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dobLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FnameShowsHere)
                            .addComponent(dobdateshow)
                            .addComponent(SSNShowsHere))
                        .addGap(38, 38, 38)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageLabel)
                                    .addComponent(contactLabel)
                                    .addComponent(heightLabel)
                                    .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LnameShowsHere)
                                    .addComponent(ContactShowsHere)
                                    .addComponent(AgeShowsHere)
                                    .addGroup(demographicPanelLayout.createSequentialGroup()
                                        .addComponent(HeightShowsHere)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))))
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(weightLabel)
                                .addGap(18, 18, 18)
                                .addComponent(WeightShowsHere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(demoInfoLabel)
                        .addGap(212, 212, 212)))
                .addGap(60, 60, 60))
        );
        demographicPanelLayout.setVerticalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(demoInfoLabel)
                .addGap(49, 49, 49)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnameLabel)
                            .addComponent(FnameShowsHere))
                        .addGap(11, 11, 11)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobLabel)
                            .addComponent(dobdateshow))
                        .addGap(22, 22, 22)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssnLabel)
                            .addComponent(SSNShowsHere)))
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameShowsHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgeShowsHere)
                            .addComponent(ageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactShowsHere))
                        .addGap(8, 8, 8)
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightLabel)
                            .addComponent(HeightShowsHere)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLabel)
                    .addComponent(WeightShowsHere)
                    .addComponent(jLabel9))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        addressGetPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addressInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressInfoLabel.setText("Address Information");

        streetAddLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        streetAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        streetAddLabel.setText("Street Address:");

        postalCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        postalCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        postalCodeLabel.setText("Postal Code:");

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cityLabel.setText("City:");

        stateLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stateLabel.setText("State:");

        StrtAddShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        StrtAddShowsHere.setText("StrtAddShowsHere");

        CityShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CityShowsHere.setText("CityShowsHere");

        StateShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        StateShowsHere.setText("StateShowsHere");

        PostalCodeShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        PostalCodeShowsHere.setText("PostalCodeShowsHere");

        javax.swing.GroupLayout addressGetPanelLayout = new javax.swing.GroupLayout(addressGetPanel);
        addressGetPanel.setLayout(addressGetPanelLayout);
        addressGetPanelLayout.setHorizontalGroup(
            addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressGetPanelLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stateLabel)
                    .addComponent(cityLabel)
                    .addComponent(streetAddLabel)
                    .addComponent(postalCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StrtAddShowsHere)
                    .addComponent(CityShowsHere)
                    .addComponent(StateShowsHere)
                    .addComponent(PostalCodeShowsHere))
                .addGap(201, 201, 201))
            .addGroup(addressGetPanelLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(addressInfoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addressGetPanelLayout.setVerticalGroup(
            addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressGetPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addressInfoLabel)
                .addGap(53, 53, 53)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetAddLabel)
                    .addComponent(StrtAddShowsHere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(CityShowsHere))
                .addGap(11, 11, 11)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(StateShowsHere))
                .addGap(18, 18, 18)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCodeLabel)
                    .addComponent(PostalCodeShowsHere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Saving Account Details");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Bank Routing Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Bank Account Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Account Balance:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Bank Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Account Type:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Checking Account Details");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Bank Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Bank Routing Number:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Bank Account Number:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Account Balance:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Account Type:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Checking");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Savings");

        SavingBnkNameShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SavingBnkNameShowsHere.setText("SavingBnkNameShowsHere");

        SavingBnkRoutingShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SavingBnkRoutingShowsHere.setText("SavingBnkRoutingShowsHere");

        SavingBnkAcctNumShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SavingBnkAcctNumShowsHere.setText("SavingBnkAcctNumShowsHere");

        SavingAcctBalShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SavingAcctBalShowsHere.setText("SavingAcctBalShowsHere");

        ChkBnkNameShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChkBnkNameShowsHere.setText("ChkBnkNameShowsHere");

        ChkBnkRoutingShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChkBnkRoutingShowsHere.setText("ChkBnkRoutingShowsHere");

        ChkBnkAcctNumShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChkBnkAcctNumShowsHere.setText("ChkBnkAcctNumShowsHere");

        ChkAcctBalShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChkAcctBalShowsHere.setText("ChkAcctBalShowsHere");

        javax.swing.GroupLayout accountDetailsPanelLayout = new javax.swing.GroupLayout(accountDetailsPanel);
        accountDetailsPanel.setLayout(accountDetailsPanelLayout);
        accountDetailsPanelLayout.setHorizontalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavingBnkNameShowsHere)
                            .addComponent(SavingBnkRoutingShowsHere)
                            .addComponent(SavingBnkAcctNumShowsHere)
                            .addComponent(SavingAcctBalShowsHere)
                            .addComponent(jLabel22)))
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDetailsPanelLayout.createSequentialGroup()
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(47, 47, 47)
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChkBnkNameShowsHere)
                                    .addComponent(ChkBnkRoutingShowsHere)
                                    .addComponent(ChkBnkAcctNumShowsHere)
                                    .addComponent(ChkAcctBalShowsHere)))
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel14)))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21)
                        .addGap(291, 291, 291))))
        );
        accountDetailsPanelLayout.setVerticalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14))
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDetailsPanelLayout.createSequentialGroup()
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SavingBnkNameShowsHere))
                        .addGap(19, 19, 19)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(SavingBnkRoutingShowsHere))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SavingBnkAcctNumShowsHere))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SavingAcctBalShowsHere))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDetailsPanelLayout.createSequentialGroup()
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addComponent(ChkBnkNameShowsHere)
                                .addGap(18, 18, 18)
                                .addComponent(ChkBnkRoutingShowsHere)
                                .addGap(18, 18, 18)
                                .addComponent(ChkBnkAcctNumShowsHere)
                                .addGap(18, 18, 18)
                                .addComponent(ChkAcctBalShowsHere))
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18))))
        );

        driverLicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        driverLicDetPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        driverLicDetPanel.setText("Driver’s License Information");

        licNumLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        licNumLbl.setText("License Number:");

        issueDateLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        issueDateLbl.setText("Date It Was Issued:");

        expiryDateLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        expiryDateLbl.setText("Date of Expiration:");

        bloodTypeLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bloodTypeLbl.setText("Blood Type:");

        LicenseNumShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LicenseNumShowsHere.setText("LicenseNumShowsHere");

        IssueDateShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        IssueDateShowsHere.setText("IssueDateShowsHere");

        ExpiryDateShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExpiryDateShowsHere.setText("ExpiryDateShowsHere");

        BloodTypeShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BloodTypeShowsHere.setText("BloodTypeShowsHere");

        javax.swing.GroupLayout driverLicPanelLayout = new javax.swing.GroupLayout(driverLicPanel);
        driverLicPanel.setLayout(driverLicPanelLayout);
        driverLicPanelLayout.setHorizontalGroup(
            driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicPanelLayout.createSequentialGroup()
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(driverLicDetPanel))
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imagedispLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueDateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licNumLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expiryDateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bloodTypeLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LicenseNumShowsHere)
                            .addComponent(IssueDateShowsHere)
                            .addComponent(ExpiryDateShowsHere)
                            .addComponent(BloodTypeShowsHere))))
                .addGap(164, 164, 164))
        );
        driverLicPanelLayout.setVerticalGroup(
            driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverLicDetPanel)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licNumLbl)
                            .addComponent(LicenseNumShowsHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueDateLbl)
                            .addComponent(IssueDateShowsHere))
                        .addGap(18, 18, 18)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expiryDateLbl)
                            .addComponent(ExpiryDateShowsHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodTypeLbl)
                            .addComponent(BloodTypeShowsHere)))
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imagedispLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        medicalPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        medicalPanelLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        medicalPanelLbl.setText("Medical Record");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Medical Record Number:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Alergy 1:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Alergy 2:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Alergy 3:");

        MedicalRecordNumShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        MedicalRecordNumShowsHere.setText("MedicalRecordNumShowsHere");

        Alergy1ShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Alergy1ShowsHere.setText("Alergy1ShowsHere");

        Alergy2ShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Alergy2ShowsHere.setText("Alergy2ShowsHere");

        Alergy3ShowsHere.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Alergy3ShowsHere.setText("Alergy3ShowsHere");

        javax.swing.GroupLayout medicalPanelLayout = new javax.swing.GroupLayout(medicalPanel);
        medicalPanel.setLayout(medicalPanelLayout);
        medicalPanelLayout.setHorizontalGroup(
            medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medicalPanelLayout.createSequentialGroup()
                        .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39)
                        .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicalRecordNumShowsHere)
                            .addComponent(Alergy2ShowsHere)
                            .addComponent(Alergy3ShowsHere)))
                    .addGroup(medicalPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel17)
                        .addGap(39, 39, 39)
                        .addComponent(Alergy1ShowsHere)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medicalPanelLbl)
                .addGap(298, 298, 298))
        );
        medicalPanelLayout.setVerticalGroup(
            medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medicalPanelLbl)
                .addGap(46, 46, 46)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(MedicalRecordNumShowsHere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Alergy1ShowsHere))
                .addGap(11, 11, 11)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Alergy2ShowsHere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Alergy3ShowsHere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Report");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel15)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setText("Create another profile");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(664, 664, 664)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accountDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(demographicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressGetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(driverLicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(demographicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressGetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverLicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 195, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        
          JFrame page1 = new UserDetailsInput();
          //JFrame report = new ReportView1(personData);
           page1.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //jPanel.setVisible(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeShowsHere;
    private javax.swing.JLabel Alergy1ShowsHere;
    private javax.swing.JLabel Alergy2ShowsHere;
    private javax.swing.JLabel Alergy3ShowsHere;
    private javax.swing.JLabel BloodTypeShowsHere;
    private javax.swing.JLabel ChkAcctBalShowsHere;
    private javax.swing.JLabel ChkBnkAcctNumShowsHere;
    private javax.swing.JLabel ChkBnkNameShowsHere;
    private javax.swing.JLabel ChkBnkRoutingShowsHere;
    private javax.swing.JLabel CityShowsHere;
    private javax.swing.JLabel ContactShowsHere;
    private javax.swing.JLabel ExpiryDateShowsHere;
    private javax.swing.JLabel FnameShowsHere;
    private javax.swing.JLabel HeightShowsHere;
    private javax.swing.JLabel IssueDateShowsHere;
    private javax.swing.JLabel LicenseNumShowsHere;
    private javax.swing.JLabel LnameShowsHere;
    private javax.swing.JLabel MedicalRecordNumShowsHere;
    private javax.swing.JLabel PostalCodeShowsHere;
    private javax.swing.JLabel SSNShowsHere;
    private javax.swing.JLabel SavingAcctBalShowsHere;
    private javax.swing.JLabel SavingBnkAcctNumShowsHere;
    private javax.swing.JLabel SavingBnkNameShowsHere;
    private javax.swing.JLabel SavingBnkRoutingShowsHere;
    private javax.swing.JLabel StateShowsHere;
    private javax.swing.JLabel StrtAddShowsHere;
    private javax.swing.JLabel WeightShowsHere;
    private javax.swing.JPanel accountDetailsPanel;
    private javax.swing.JPanel addressGetPanel;
    private javax.swing.JLabel addressInfoLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bloodTypeLbl;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel demoInfoLabel;
    private javax.swing.JPanel demographicPanel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobdateshow;
    private javax.swing.JLabel driverLicDetPanel;
    private javax.swing.JPanel driverLicPanel;
    private javax.swing.JLabel expiryDateLbl;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel imagedispLbl;
    private javax.swing.JLabel issueDateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licNumLbl;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JPanel medicalPanel;
    private javax.swing.JLabel medicalPanelLbl;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel streetAddLabel;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
