/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aed_assignment1;

import DAO.PersonDetails;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import javax.swing.ImageIcon;


/**
 *
 * @author Vaishali Tripathi
 */
public class UserDetailsInput extends javax.swing.JFrame {

    /**
     * Creates new form UserDetails
     */
    private PersonDetails personData;
    public UserDetailsInput() {
        initComponents();
        PersonDetails personData = new PersonDetails();
        demographicPanel.setVisible(true);
        addressGetPanel.setVisible(false);
        accountDetailsPanel.setVisible(false);
        driverLicPanel.setVisible(false);
        medicalPanel.setVisible(false);
    

    }

    /*
    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        demographicPanel = new javax.swing.JPanel();
        demoInfoLabel = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        dobTxt = new javax.swing.JTextField();
        fnameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        ssnchkBtn = new javax.swing.JCheckBox();
        ssnTxt = new javax.swing.JTextField();
        saveDemoInfoBtn = new javax.swing.JButton();
        clrDemoInfoBtn = new javax.swing.JButton();
        weightTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        heightTxt = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        addressGetPanel = new javax.swing.JPanel();
        addressInfoLabel = new javax.swing.JLabel();
        streetAddLabel = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        streetAddTxt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        stateTxt = new javax.swing.JTextField();
        postalCodeTxt = new javax.swing.JTextField();
        clrAddressDetaiulsBtn = new javax.swing.JButton();
        saveAddressBtn = new javax.swing.JButton();
        accountDetailsPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        savingBankNameTxt = new javax.swing.JTextField();
        savingRoutingTxt = new javax.swing.JTextField();
        savingActNumTxt = new javax.swing.JTextField();
        savingActBalTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chkBankNameTxt = new javax.swing.JTextField();
        ChkRoutingTxt = new javax.swing.JTextField();
        ChkActNumTxt = new javax.swing.JTextField();
        chkActBalTxt = new javax.swing.JTextField();
        isSameAsSavingAcc = new javax.swing.JCheckBox();
        saveNewAcctBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        clrAccDetBtn1 = new javax.swing.JButton();
        driverLicPanel = new javax.swing.JPanel();
        driverLicDetPanel = new javax.swing.JLabel();
        licNumLbl = new javax.swing.JLabel();
        issueDateLbl = new javax.swing.JLabel();
        expiryDateLbl = new javax.swing.JLabel();
        bloodTypeLbl = new javax.swing.JLabel();
        pictureLbl = new javax.swing.JLabel();
        licNumTxt = new javax.swing.JTextField();
        issueDateTxt = new javax.swing.JTextField();
        expiryDateTxt = new javax.swing.JTextField();
        bloodTypeTxt = new javax.swing.JTextField();
        imageURLTxt = new javax.swing.JTextField();
        saveLicDetPanelBtn = new javax.swing.JButton();
        clrLicDetPanelBtn = new javax.swing.JButton();
        uploadImgBtn = new javax.swing.JButton();
        medicalPanel = new javax.swing.JPanel();
        medicalPanelLbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        saveMedicalBtn = new javax.swing.JButton();
        alergy3Txt = new javax.swing.JTextField();
        alergy2Txt = new javax.swing.JTextField();
        alergy1Txt = new javax.swing.JTextField();
        medicalRecordNumTxt = new javax.swing.JTextField();
        viewDetailsBtn = new javax.swing.JButton();
        clrMedRcdBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        demographicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        demoInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        demoInfoLabel.setText("Demographic Information");

        fnameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtActionPerformed(evt);
            }
        });

        dobTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dobTxt.setText("MM/DD/YYYY");
        dobTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dobTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobTxtFocusLost(evt);
            }
        });
        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });

        fnameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fnameLabel.setText("First Name:");

        dobLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dobLabel.setText("Date of Birth:");

        ssnLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ssnLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ssnLabel.setText("Social Security Number:");

        ssnchkBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ssnchkBtn.setText("I do not have a social security number");
        ssnchkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnchkBtnActionPerformed(evt);
            }
        });
        ssnchkBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ssnchkBtnKeyPressed(evt);
            }
        });

        ssnTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        saveDemoInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveDemoInfoBtn.setText("Save");
        saveDemoInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDemoInfoBtnActionPerformed(evt);
            }
        });

        clrDemoInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clrDemoInfoBtn.setText("Clear All");
        clrDemoInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrDemoInfoBtnActionPerformed(evt);
            }
        });

        weightTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("kgs");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("cms");

        heightTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        heightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTxtActionPerformed(evt);
            }
        });

        heightLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        heightLabel.setText("Height:");

        weightLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        weightLabel.setText("Weight:");

        contactLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        contactLabel.setText("Contact Number:");

        ageLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ageLabel.setText("Age:");
        ageLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lnameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnameLabel.setText("Last Name:");

        lnameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        agetxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        agetxt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        contactTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        contactTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactTxtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout demographicPanelLayout = new javax.swing.GroupLayout(demographicPanel);
        demographicPanel.setLayout(demographicPanelLayout);
        demographicPanelLayout.setHorizontalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ssnLabel)
                                    .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dobLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(18, 18, 18)
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnameTxt)
                                    .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(ssnchkBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(demographicPanelLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(contactLabel)
                                            .addComponent(heightLabel)
                                            .addComponent(weightLabel)))
                                    .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demographicPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(240, 240, 240))
                                    .addGroup(demographicPanelLayout.createSequentialGroup()
                                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel9))
                                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(heightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(244, 244, 244))))
                            .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addComponent(saveDemoInfoBtn)
                                .addGap(64, 64, 64)
                                .addComponent(clrDemoInfoBtn))
                            .addGroup(demographicPanelLayout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(demoInfoLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        demographicPanelLayout.setVerticalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demoInfoLabel)
                .addGap(25, 25, 25)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dobLabel)
                        .addComponent(ageLabel))
                    .addGroup(demographicPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnLabel)
                    .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnchkBtn)
                    .addComponent(heightLabel)
                    .addComponent(heightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLabel)
                    .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(58, 58, 58)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDemoInfoBtn)
                    .addComponent(clrDemoInfoBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addressGetPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addressInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressInfoLabel.setText("Address Information");

        streetAddLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        streetAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        streetAddLabel.setText("Street Address:");

        postalCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        postalCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        postalCodeLabel.setText("Postal Code:");

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cityLabel.setText("City:");

        stateLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stateLabel.setText("State:");

        streetAddTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        streetAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetAddTxtActionPerformed(evt);
            }
        });

        cityTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        stateTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        postalCodeTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        clrAddressDetaiulsBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clrAddressDetaiulsBtn.setText("Clear All");
        clrAddressDetaiulsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrAddressDetaiulsBtnActionPerformed(evt);
            }
        });

        saveAddressBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveAddressBtn.setText("Save");
        saveAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddressBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressGetPanelLayout = new javax.swing.GroupLayout(addressGetPanel);
        addressGetPanel.setLayout(addressGetPanelLayout);
        addressGetPanelLayout.setHorizontalGroup(
            addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressGetPanelLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(saveAddressBtn)
                .addGap(50, 50, 50)
                .addComponent(clrAddressDetaiulsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressGetPanelLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressGetPanelLayout.createSequentialGroup()
                        .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stateLabel)
                            .addComponent(cityLabel)
                            .addComponent(streetAddLabel)
                            .addComponent(postalCodeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(postalCodeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressGetPanelLayout.createSequentialGroup()
                        .addComponent(addressInfoLabel)
                        .addGap(288, 288, 288))))
        );
        addressGetPanelLayout.setVerticalGroup(
            addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressGetPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addressInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetAddLabel)
                    .addComponent(streetAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postalCodeLabel)
                    .addComponent(postalCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(addressGetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAddressBtn)
                    .addComponent(clrAddressDetaiulsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Saving Account Details");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Bank Routing Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Bank Account Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Account Balance:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Bank Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Account Type:");

        savingBankNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        savingBankNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingBankNameTxtActionPerformed(evt);
            }
        });

        savingRoutingTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        savingRoutingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingRoutingTxtActionPerformed(evt);
            }
        });

        savingActNumTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        savingActBalTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Checking Account Details");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Bank Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Bank Routing Number:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Bank Account Number:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Account Balance:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Account Type:");

        chkBankNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        chkBankNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBankNameTxtActionPerformed(evt);
            }
        });

        ChkRoutingTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChkRoutingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkRoutingTxtActionPerformed(evt);
            }
        });

        ChkActNumTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        chkActBalTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        isSameAsSavingAcc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        isSameAsSavingAcc.setText("Same as Saving Account");
        isSameAsSavingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSameAsSavingAccActionPerformed(evt);
            }
        });

        saveNewAcctBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveNewAcctBtn.setText("Save");
        saveNewAcctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewAcctBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Checking");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Savings");

        clrAccDetBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clrAccDetBtn1.setText("Clear All");
        clrAccDetBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrAccDetBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountDetailsPanelLayout = new javax.swing.GroupLayout(accountDetailsPanel);
        accountDetailsPanel.setLayout(accountDetailsPanelLayout);
        accountDetailsPanelLayout.setHorizontalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(savingBankNameTxt)
                                            .addComponent(savingRoutingTxt)
                                            .addComponent(savingActNumTxt)
                                            .addComponent(savingActBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel22))))
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addComponent(jLabel13)))
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGap(478, 478, 478)
                                .addComponent(jLabel14))
                            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isSameAsSavingAcc)
                                    .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel21)
                                        .addComponent(ChkActNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                        .addComponent(ChkRoutingTxt)
                                        .addComponent(chkBankNameTxt)
                                        .addComponent(chkActBalTxt))))))
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGap(827, 827, 827)
                        .addComponent(saveNewAcctBtn)
                        .addGap(111, 111, 111)
                        .addComponent(clrAccDetBtn1)))
                .addGap(102, 102, 102))
        );
        accountDetailsPanelLayout.setVerticalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDetailsPanelLayout.createSequentialGroup()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(savingBankNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(savingRoutingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(savingActNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(savingActBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22)))
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isSameAsSavingAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chkBankNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ChkRoutingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ChkActNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(chkActBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel21))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrAccDetBtn1)
                    .addComponent(saveNewAcctBtn))
                .addContainerGap())
        );

        driverLicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        driverLicDetPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        driverLicDetPanel.setText("Driver’s License Information");

        licNumLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        licNumLbl.setText("License Number:");

        issueDateLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        issueDateLbl.setText("Date It Was Issued:");

        expiryDateLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        expiryDateLbl.setText("Date of Expiration:");

        bloodTypeLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bloodTypeLbl.setText("Blood Type:");

        pictureLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pictureLbl.setText("Picture:");

        licNumTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        issueDateTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        issueDateTxt.setText("MM/DD/YYYY");
        issueDateTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issueDateTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issueDateTxtFocusLost(evt);
            }
        });
        issueDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDateTxtActionPerformed(evt);
            }
        });

        expiryDateTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        expiryDateTxt.setText("MM/DD/YYYY");
        expiryDateTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expiryDateTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expiryDateTxtFocusLost(evt);
            }
        });

        bloodTypeTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        imageURLTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        imageURLTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageURLTxtActionPerformed(evt);
            }
        });

        saveLicDetPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveLicDetPanelBtn.setText("Save");
        saveLicDetPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLicDetPanelBtnActionPerformed(evt);
            }
        });

        clrLicDetPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clrLicDetPanelBtn.setText("Clear All");
        clrLicDetPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrLicDetPanelBtnActionPerformed(evt);
            }
        });

        uploadImgBtn.setText("Upload");
        uploadImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverLicPanelLayout = new javax.swing.GroupLayout(driverLicPanel);
        driverLicPanel.setLayout(driverLicPanelLayout);
        driverLicPanelLayout.setHorizontalGroup(
            driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverLicPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(driverLicDetPanel)
                .addGap(371, 371, 371))
            .addGroup(driverLicPanelLayout.createSequentialGroup()
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licNumLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(issueDateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expiryDateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bloodTypeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pictureLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39)
                        .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(licNumTxt)
                            .addComponent(issueDateTxt)
                            .addComponent(expiryDateTxt)
                            .addComponent(bloodTypeTxt)
                            .addComponent(imageURLTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadImgBtn))
                    .addGroup(driverLicPanelLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(saveLicDetPanelBtn)
                        .addGap(38, 38, 38)
                        .addComponent(clrLicDetPanelBtn)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        driverLicPanelLayout.setVerticalGroup(
            driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(driverLicDetPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licNumLbl)
                    .addComponent(licNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueDateLbl)
                    .addComponent(issueDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateLbl)
                    .addComponent(expiryDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeLbl)
                    .addComponent(bloodTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pictureLbl)
                    .addComponent(imageURLTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImgBtn))
                .addGap(18, 18, 18)
                .addGroup(driverLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveLicDetPanelBtn)
                    .addComponent(clrLicDetPanelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        medicalPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        medicalPanelLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        medicalPanelLbl.setText("Medical Record");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Medical Record Number:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Alergy 1:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Alergy 2:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Alergy 3:");

        saveMedicalBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveMedicalBtn.setText("Save");
        saveMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMedicalBtnActionPerformed(evt);
            }
        });

        alergy3Txt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        alergy2Txt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        alergy1Txt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        medicalRecordNumTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        viewDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        clrMedRcdBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clrMedRcdBtn.setText("Clear All");
        clrMedRcdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrMedRcdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout medicalPanelLayout = new javax.swing.GroupLayout(medicalPanel);
        medicalPanel.setLayout(medicalPanelLayout);
        medicalPanelLayout.setHorizontalGroup(
            medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalPanelLayout.createSequentialGroup()
                        .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(medicalPanelLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(saveMedicalBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clrMedRcdBtn)
                                .addGap(69, 69, 69)
                                .addComponent(viewDetailsBtn))
                            .addGroup(medicalPanelLayout.createSequentialGroup()
                                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39)
                                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medicalRecordNumTxt)
                                    .addComponent(alergy1Txt)
                                    .addComponent(alergy2Txt)
                                    .addComponent(alergy3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalPanelLayout.createSequentialGroup()
                        .addComponent(medicalPanelLbl)
                        .addGap(286, 286, 286))))
        );
        medicalPanelLayout.setVerticalGroup(
            medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(medicalPanelLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(medicalRecordNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(alergy1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(alergy2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(alergy3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(medicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveMedicalBtn)
                    .addComponent(viewDetailsBtn)
                    .addComponent(clrMedRcdBtn))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(driverLicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(accountDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(demographicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressGetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1835, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(demographicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressGetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medicalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTxtActionPerformed

    private void dobTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobTxtFocusGained
        // TODO add your handling code here:
        dobTxt.setText("");
    }//GEN-LAST:event_dobTxtFocusGained

    private void dobTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobTxtFocusLost
        // TODO add your handling code here:

        Date dateofbirth;
        try {
            dateofbirth = new SimpleDateFormat("MM/dd/yyyy").parse(dobTxt.getText());
            agetxt.setText(Long.toString(calculateAge(dateofbirth)));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter date in mm/dd/yyyy format.");
            dobTxt.setText("");
            agetxt.setText("");

        }

        // age.setText("autopopulate age here");
    }//GEN-LAST:event_dobTxtFocusLost

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTxtActionPerformed

    private void ssnchkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnchkBtnActionPerformed
        // TODO add your handling code here:
        if (ssnchkBtn.isSelected()) {
            ssnTxt.setEnabled(false);
            ssnTxt.setText("");
        } else {
            ssnTxt.setEnabled(true);
        }
    }//GEN-LAST:event_ssnchkBtnActionPerformed

    private void ssnchkBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnchkBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnchkBtnKeyPressed

    private void saveDemoInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDemoInfoBtnActionPerformed
        // TODO add your handling code here:
        addressGetPanel.setVisible(true);
        fnameTxt.setEnabled(false);
        lnameTxt.setEnabled(false);
        dobTxt.setEnabled(false);
        ssnTxt.setEnabled(false);
        contactTxt.setEnabled(false);
        heightTxt.setEnabled(false);
        weightTxt.setEnabled(false);
        saveDemoInfoBtn.setEnabled(false);
        

        
    }//GEN-LAST:event_saveDemoInfoBtnActionPerformed

    private void clrDemoInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrDemoInfoBtnActionPerformed
        // TODO add your handling code here:
        clearDemographic();
        saveDemoInfoBtn.setEnabled(true);
    }//GEN-LAST:event_clrDemoInfoBtnActionPerformed

    private void heightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTxtActionPerformed

    private void contactTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtFocusLost

    private void streetAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetAddTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetAddTxtActionPerformed

    private void clrAddressDetaiulsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrAddressDetaiulsBtnActionPerformed
        // TODO add your handling code here:
        saveAddressBtn.setEnabled(true);
        clearAddressPanel();
    }//GEN-LAST:event_clrAddressDetaiulsBtnActionPerformed

    private void saveAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddressBtnActionPerformed
        // TODO add your handling code here:
        saveAddressBtn.setEnabled(false);
        accountDetailsPanel.setVisible(true);
        streetAddTxt.setEnabled(false);
        cityTxt.setEnabled(false);
        stateTxt.setEnabled(false);
        postalCodeTxt.setEnabled(false);
    }//GEN-LAST:event_saveAddressBtnActionPerformed

    private void savingBankNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingBankNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingBankNameTxtActionPerformed

    private void savingRoutingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingRoutingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingRoutingTxtActionPerformed

    private void chkBankNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBankNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBankNameTxtActionPerformed

    private void ChkRoutingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkRoutingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkRoutingTxtActionPerformed

    private void isSameAsSavingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSameAsSavingAccActionPerformed
        // TODO add your handling code here:
        ChkActNumTxt.setText(savingActNumTxt.getText());
        ChkRoutingTxt.setText(savingRoutingTxt.getText());
        chkActBalTxt.setText(savingActBalTxt.getText());
        chkBankNameTxt.setText(savingBankNameTxt.getText());
    }//GEN-LAST:event_isSameAsSavingAccActionPerformed

    private void saveNewAcctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewAcctBtnActionPerformed
        // TODO add your handling code here:
        //clearAccountPanel();
        saveNewAcctBtn.setEnabled(false);
        savingBankNameTxt.setEnabled(false);
        savingRoutingTxt.setEnabled(false);
        savingActNumTxt.setEnabled(false);
        savingActBalTxt.setEnabled(false);
        chkBankNameTxt.setEnabled(false);
        ChkRoutingTxt.setEnabled(false);
        ChkActNumTxt.setEnabled(false);
        chkActBalTxt.setEnabled(false);
        isSameAsSavingAcc.setEnabled(false);
        driverLicPanel.setVisible(true);
    }//GEN-LAST:event_saveNewAcctBtnActionPerformed

    private void imageURLTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageURLTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageURLTxtActionPerformed

    private void saveLicDetPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLicDetPanelBtnActionPerformed
        // TODO add your handling code here:
        saveLicDetPanelBtn.setEnabled(false);
        licNumTxt.setEnabled(false);
        issueDateTxt.setEnabled(false);
        expiryDateTxt.setEnabled(false);
        bloodTypeTxt.setEnabled(false);
        imageURLTxt.setEditable(false);
        medicalPanel.setVisible(true);
        viewDetailsBtn.setEnabled(false);
        
    }//GEN-LAST:event_saveLicDetPanelBtnActionPerformed

    private void clrLicDetPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrLicDetPanelBtnActionPerformed
        // TODO add your handling code here:
        clearLicDetailsPanel();
        saveLicDetPanelBtn.setEnabled(true);
        licNumTxt.setEnabled(true);
        issueDateTxt.setEnabled(true);
        expiryDateTxt.setEnabled(true);
        bloodTypeTxt.setEnabled(true);
        imageURLTxt.setEnabled(true);
        
        licNumTxt.setText("");
        issueDateTxt.setText("");
        expiryDateTxt.setText("");
        bloodTypeTxt.setText("");
        imageURLTxt.setText("");
    }//GEN-LAST:event_clrLicDetPanelBtnActionPerformed

    private void clrAccDetBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrAccDetBtn1ActionPerformed
        // TODO add your handling code here:
        saveNewAcctBtn.setEnabled(true);
        savingBankNameTxt.setEnabled(true);
        savingRoutingTxt.setEnabled(true);
        savingActNumTxt.setEnabled(true);
        savingActBalTxt.setEnabled(true);
        chkBankNameTxt.setEnabled(true);
        ChkRoutingTxt.setEnabled(true);
        ChkActNumTxt.setEnabled(true);
        chkActBalTxt.setEnabled(true);
        isSameAsSavingAcc.setEnabled(true);
        isSameAsSavingAcc.setVisible(true);
        
        savingBankNameTxt.setText("");
        savingRoutingTxt.setText("");
        savingActNumTxt.setText("");
       
        savingActBalTxt.setText("");
        chkBankNameTxt.setText("");
        ChkRoutingTxt.setText("");
        ChkActNumTxt.setText("");
        chkActBalTxt.setText("");
        
    }//GEN-LAST:event_clrAccDetBtn1ActionPerformed

    private void saveMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMedicalBtnActionPerformed
        // TODO add your handling code here:
        //saveNewAcctBtn.setVisible(false);
        medicalRecordNumTxt.setEnabled(false);
        alergy1Txt.setEnabled(false);
        alergy2Txt.setEnabled(false);
        alergy3Txt.setEnabled(false);
        
        viewDetailsBtn.setEnabled(true);
        
    }//GEN-LAST:event_saveMedicalBtnActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        
        PersonDetails personData  = CreatePersonDetailObj();
          JFrame report = new ReportView1(personData);
          //JFrame report = new ReportView1(personData);
           report.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void clrMedRcdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrMedRcdBtnActionPerformed
        // TODO add your handling code here:
        medicalRecordNumTxt.setEnabled(true);
        alergy1Txt.setEnabled(true);
        alergy2Txt.setEnabled(true);
        alergy3Txt.setEnabled(true);
        chkBankNameTxt.setEnabled(true);
        
        medicalRecordNumTxt.setText("");
        alergy1Txt.setText("");
        alergy2Txt.setText("");
        alergy3Txt.setText("");
        chkBankNameTxt.setText("");
        saveMedicalBtn.setEnabled(true);
        viewDetailsBtn.setEnabled(false);
        
    }//GEN-LAST:event_clrMedRcdBtnActionPerformed

    private void uploadImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        imageURLTxt.setText(filename);
        
        
        
        
    }//GEN-LAST:event_uploadImgBtnActionPerformed

    private void expiryDateTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiryDateTxtFocusLost
        // TODO add your handling code here:
        Date expiryDate;
        try {
            expiryDate = new SimpleDateFormat("MM/dd/yyyy").parse(expiryDateTxt.getText());
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter date in mm/dd/yyyy format.");
            expiryDateTxt.setText("");

        }
    }//GEN-LAST:event_expiryDateTxtFocusLost

    private void issueDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueDateTxtActionPerformed

    private void issueDateTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issueDateTxtFocusLost
        // TODO add your handling code here:
        Date issueDate;
        try {
            issueDate = new SimpleDateFormat("MM/dd/yyyy").parse(issueDateTxt.getText());
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter date in mm/dd/yyyy format.");
            issueDateTxt.setText("");

        }
    }//GEN-LAST:event_issueDateTxtFocusLost

    private void issueDateTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issueDateTxtFocusGained
        // TODO add your handling code here:
        issueDateTxt.setText("");
    }//GEN-LAST:event_issueDateTxtFocusGained

    private void expiryDateTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiryDateTxtFocusGained
        // TODO add your handling code here:
        expiryDateTxt.setText("");
    }//GEN-LAST:event_expiryDateTxtFocusGained
   private PersonDetails CreatePersonDetailObj() {

       
            PersonDetails detail = new PersonDetails();
//Demographic Info
            detail.setFname(fnameTxt.getText());
            detail.setLname(lnameTxt.getText());
            
 try {
            Date date1 = new SimpleDateFormat("MM/dd/yyyy").parse(dobTxt.getText());
     
          
        } catch (ParseException ex) {
            System.out.print(ex);
        }
 
            detail.setDate1Str(dobTxt.getText());
            detail.setContact(contactTxt.getText());
            detail.setSSN(ssnTxt.getText());
            detail.setHeight(heightTxt.getText());
            detail.setWeight(weightTxt.getText());
            
            
            //Address Details
            
            detail.setStreetAdd(streetAddTxt.getText());
            detail.setState(stateTxt.getText());
            detail.setCity(cityTxt.getText());
            detail.setZipCode(postalCodeTxt.getText());
            
            //Saving Account Details
            detail.setSavingBankName(savingBankNameTxt.getText());
            detail.setSavingBankRouting(savingRoutingTxt.getText());
            detail.setSavingBankBalance(savingActBalTxt.getText());
            detail.setSavingBankAccNum(savingActBalTxt.getText());
            
            //Checking Account Details
            detail.setCheckingBankAccNum(ChkActNumTxt.getText());
            detail.setCheckingBankBalance(chkActBalTxt.getText());
            detail.setCheckingBankName(chkBankNameTxt.getText());
            detail.setCheckingBankRouting(ChkRoutingTxt.getText());
            
            //License Details
            detail.setLicenseNum(licNumTxt.getText());
            
            try {
            Date LicenseIssueDate = new SimpleDateFormat("MM/dd/yyyy").parse(issueDateTxt.getText());
          
        } catch (ParseException ex) {
            System.out.print(ex);
        }
            try {
            Date LicenseIssueDate = new SimpleDateFormat("MM/dd/yyyy").parse(expiryDateTxt.getText());
          
        } catch (ParseException ex) {
            System.out.print(ex);
        }
            
            
            detail.setIssueDateStr(issueDateTxt.getText());
            detail.setExpiryDateStr(expiryDateTxt.getText());
            detail.setBloodType(bloodTypeTxt.getText());
            detail.setImageURL(imageURLTxt.getText());
            
            //Medical Record
            detail.setMedicalRecordNum(medicalRecordNumTxt.getText());
            detail.setAlergy1(alergy1Txt.getText());
            detail.setAlergy2(alergy2Txt.getText());
            detail.setAlergy3(alergy3Txt.getText());
            
            
            
       
            return detail;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetailsInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetailsInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetailsInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetailsInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserDetailsInput().setVisible(true);
        });
    }

    private int calculateAge(Date dob) {
        Date currentDate = new Date();
        float diffDays = (currentDate.getTime() - dob.getTime()) / ((1000 * 60 * 60 * 24));
        int diffYears = (int) (diffDays / 365);
        return diffYears;
    }

    private void clearDemographic() {
        fnameTxt.setText("");
        lnameTxt.setText("");
        dobTxt.setText("");
        agetxt.setText("");
        ssnTxt.setText("");
        contactTxt.setText("");
        heightTxt.setText("");
        weightTxt.setText("");
        ssnchkBtn.setEnabled(false);
        ssnTxt.setEnabled(true);
        fnameTxt.setEnabled(true);
        lnameTxt.setEnabled(true);
        dobTxt.setEnabled(true);
        agetxt.setEnabled(true);
        ssnTxt.setEnabled(true);
        contactTxt.setEnabled(true);
        heightTxt.setEnabled(true);
        weightTxt.setEnabled(true);
        ssnchkBtn.setEnabled(true);
    }

    private void clearAddressPanel() {
        streetAddTxt.setText("");
        cityTxt.setText("");
        stateTxt.setText("");
        postalCodeTxt.setText("");
        streetAddTxt.setEnabled(true);
        cityTxt.setEnabled(true);
        stateTxt.setEnabled(true);
        postalCodeTxt.setEnabled(true);
    }

    private void clearAccountPanel() {
        saveNewAcctBtn.setEnabled(true);
        savingBankNameTxt.setText("");
        savingRoutingTxt.setText("");
        savingActNumTxt.setText("");
        savingActBalTxt.setText("");
        chkBankNameTxt.setText("");
        ChkRoutingTxt.setText("");
        ChkActNumTxt.setText("");
        chkActBalTxt.setText("");
        isSameAsSavingAcc.setText("");

        savingBankNameTxt.setEnabled(true);
        savingRoutingTxt.setEnabled(true);
        savingActNumTxt.setEnabled(true);
        savingActBalTxt.setEnabled(true);
        chkBankNameTxt.setEnabled(true);
        ChkRoutingTxt.setEnabled(true);
        ChkActNumTxt.setEnabled(true);
        chkActBalTxt.setEnabled(true);
        isSameAsSavingAcc.setEnabled(true);

    }

    private void clearLicDetailsPanel() {

        licNumTxt.setVisible(true);
        issueDateTxt.setVisible(true);
        expiryDateTxt.setVisible(true);
        bloodTypeTxt.setVisible(true);
        imageURLTxt.setVisible(true);

        licNumTxt.setText("");
        issueDateTxt.setText("");
        expiryDateTxt.setText("");
        bloodTypeTxt.setText("");
        imageURLTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChkActNumTxt;
    private javax.swing.JTextField ChkRoutingTxt;
    private javax.swing.JPanel accountDetailsPanel;
    private javax.swing.JPanel addressGetPanel;
    private javax.swing.JLabel addressInfoLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel agetxt;
    private javax.swing.JTextField alergy1Txt;
    private javax.swing.JTextField alergy2Txt;
    private javax.swing.JTextField alergy3Txt;
    private javax.swing.JLabel bloodTypeLbl;
    private javax.swing.JTextField bloodTypeTxt;
    private javax.swing.JTextField chkActBalTxt;
    private javax.swing.JTextField chkBankNameTxt;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton clrAccDetBtn1;
    private javax.swing.JButton clrAddressDetaiulsBtn;
    private javax.swing.JButton clrDemoInfoBtn;
    private javax.swing.JButton clrLicDetPanelBtn;
    private javax.swing.JButton clrMedRcdBtn;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JLabel demoInfoLabel;
    private javax.swing.JPanel demographicPanel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel driverLicDetPanel;
    private javax.swing.JPanel driverLicPanel;
    private javax.swing.JLabel expiryDateLbl;
    private javax.swing.JTextField expiryDateTxt;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTxt;
    private javax.swing.JTextField imageURLTxt;
    private javax.swing.JCheckBox isSameAsSavingAcc;
    private javax.swing.JLabel issueDateLbl;
    private javax.swing.JTextField issueDateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel licNumLbl;
    private javax.swing.JTextField licNumTxt;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JPanel medicalPanel;
    private javax.swing.JLabel medicalPanelLbl;
    private javax.swing.JTextField medicalRecordNumTxt;
    private javax.swing.JLabel pictureLbl;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField postalCodeTxt;
    private javax.swing.JButton saveAddressBtn;
    private javax.swing.JButton saveDemoInfoBtn;
    private javax.swing.JButton saveLicDetPanelBtn;
    private javax.swing.JButton saveMedicalBtn;
    private javax.swing.JButton saveNewAcctBtn;
    private javax.swing.JTextField savingActBalTxt;
    private javax.swing.JTextField savingActNumTxt;
    private javax.swing.JTextField savingBankNameTxt;
    private javax.swing.JTextField savingRoutingTxt;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnTxt;
    private javax.swing.JCheckBox ssnchkBtn;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel streetAddLabel;
    private javax.swing.JTextField streetAddTxt;
    private javax.swing.JButton uploadImgBtn;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTxt;
    // End of variables declaration//GEN-END:variables
}
